spring:
  application:
    name: cards-app
  datasource:
    url: jdbc:mysql://localhost:3306/cards_snapshot?useSSL=false
    username: root
    password: Pass123
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

tokenSecret: card24kjljtrt